
encoding: UTF-8
title: Çağlayan Demirci
email: demircicaglayan13@gmail.com
description: >-
  My name is Çağlayan Demirci and this is my personal website
  which is including software I made, information about me and
  some of my blog posts.
baseurl: ""
url: "https://cademirci.github.io/"
permalink: /:title
twitter_username: cademirci
github_username: cademirci
instagram_username: cademirci
markdown: kramdown
kramdown:
  math_engine: mathjax
sass:
    load_paths: assets/css/_sass
defaults:
  - scope: # static files
      path: "assets/images"
    values:
      image: true

plugins:
  - jekyll-feed # RSS feed
  - jekyll-sitemap
  - jekyll-seo-tag # Google analytics

collections:
    - projects

# May be I will activate this later.
# But now I did it in .git/info/exclude
#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
